version: '3'

services:
  srv:
    &srv
    container_name: silulus-app
    image: silulus-app
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_URL: redis://db2:6379
    ports:
      - 80:3000
    volumes:
      - ./public:/app/public
    depends_on:
      - db
      - db2
  # ! Uncomment to duplicate
  # srv2:
  #   <<: *srv
  #   container_name: silulus-app-2
  #   ports:
  #     - 81:3000
  gen:
    profiles:
      - migrate
    container_name: silulus-gen
    image: silulus-gen
    build:
      dockerfile: Dockerfile.prisma
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma

  db:
    container_name: silulus-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
  db2:
    container_name: silulus-db
    image: redis:6.0-alpine
    volumes:
      - data2:/data

volumes:
  data:
    driver: local
    name: silulus-postgres
  data2:
    driver: local
    name: silulus-redis