version: '3'

services:
  srv:
    &srv
    container_name: silulus-app
    image: silulus-app
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD}@db:5432/silulus?schema=public
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD} 
    ports:
      - 80:3000
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    depends_on:
      - db
  # ! Uncomment to duplicate
  # srv2:
  #   <<: *srv
  #   container_name: silulus-app-2
  #   ports:
  #     - 81:3000
  gen:
    profiles:
      - migrate
    container_name: silulus-gen
    image: silulus-gen
    build:
      dockerfile: Dockerfile.prisma
    environment:
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD}@db:5432/silulus?schema=public
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma

  db:
    container_name: silulus-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: silulus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
    name: silulus